"""empty message

Revision ID: 1520bf598f54
Revises: 
Create Date: 2021-02-18 11:19:52.918827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1520bf598f54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menuitems', ['flavour', 'category_id'])
    op.create_foreign_key(None, 'orderitems', 'menuitems', ['menuitem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'menuitems', type_='unique')
    # ### end Alembic commands ###
