"""empty message

Revision ID: 526f190d3434
Revises: 6cfe85bd55b8
Create Date: 2021-02-18 19:57:04.464960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526f190d3434'
down_revision = '6cfe85bd55b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menuitems', ['flavour', 'category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menuitems', type_='unique')
    # ### end Alembic commands ###
