"""empty message

Revision ID: 6707a6f32c07
Revises: 
Create Date: 2021-02-25 01:02:57.771344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6707a6f32c07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuitems', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('menuitems', sa.Column('flavour', sa.String(length=50), nullable=False))
    op.drop_constraint('menuitems_name_key', 'menuitems', type_='unique')
    op.create_foreign_key(None, 'menuitems', 'menuitem_categories', ['category_id'], ['id'])
    op.drop_column('menuitems', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuitems', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menuitems', type_='foreignkey')
    op.create_unique_constraint('menuitems_name_key', 'menuitems', ['name'])
    op.drop_column('menuitems', 'flavour')
    op.drop_column('menuitems', 'category_id')
    # ### end Alembic commands ###
