"""empty message

Revision ID: 6cfe85bd55b8
Revises: 1520bf598f54
Create Date: 2021-02-18 15:54:33.217634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfe85bd55b8'
down_revision = '1520bf598f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menuitems_flavour_category_id_key', 'menuitems', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('menuitems_flavour_category_id_key', 'menuitems', ['flavour', 'category_id'])
    # ### end Alembic commands ###
